### ISSUE TITLE
Errors on site without expected parameters set

### ISSUE THREAD

**Issue by paskal** [jchatkinson/HugoMDL#15]
Hello!

$subj, when trying to run this theme against my [blog](https://github.com/paskal/terrty/tree/master/blog) source I get following:

```
Building sites … ERROR 2018/03/20 16:00:28 Error while rendering "home" in "": template: theme/index.html:4:20: executing "theme/index.html" at <partial "postsnippet...>: error calling partial: template: theme/partials/postsnippets.html:1:30: executing "theme/partials/postsnippets.html" at <first .Site.Params.f...>: error calling first: both limit and seq must be provided
```

The reason is likely some absent `.Site.` parameter but you can't tell it from error message, I guess input parameters handling could be improved.
Main page doesn't render, however, single post pages are rendered. hugo version:

    Hugo Static Site Generator v0.37 linux/amd64 BuildDate: 2018-02-27T09:15:25Z

**Comment by paskal** [comment]
https://github.com/hivickylai/hugo-theme-sam/pull/3 is an example of how this can be fixed.

**Comment by MattMattV** [comment]
@jchatkinson no problem if I submit a PR to fix that issue ? 

My work would consist of fetching missing `.Parms` in `.Site.Param` and in possible cases, put a relevant default value, that would simplify a lot usage of the theme.

If you have any suggestion of things I could also do by the same time, please say me !

**Comment by jchatkinson** [comment]
Go for it!
